import { FacilityCategoryOption, FacilityDetail } from "./types";

export const facilityCategories: FacilityCategoryOption[] = [
  { facilityCount: 8, iconHint: "auditorium", id: "cat-auditorium", name: "Auditorium", slug: "auditorium" },
  { facilityCount: 12, iconHint: "classroom", id: "cat-classroom", name: "Ruang Kelas", slug: "ruang-kelas" },
  { facilityCount: 6, iconHint: "lab", id: "cat-lab", name: "Laboratorium", slug: "laboratorium" },
  { facilityCount: 5, iconHint: "meeting", id: "cat-meeting", name: "Ruang Rapat", slug: "ruang-rapat" },
  { facilityCount: 4, iconHint: "outdoor", id: "cat-outdoor", name: "Ruang Terbuka", slug: "ruang-terbuka" },
];

export const facilityDetails: FacilityDetail[] = [
  {
    capacity: 1200,
    category: "Auditorium",
    categorySlug: "auditorium",
    contact: {
      email: "ccr@apps.ipb.ac.id",
      name: "Unit Layanan CCR",
      phone: "0251-8622642",
    },
    coverImageUrl: "fixture:auditorium",
    description:
      "Auditorium utama untuk wisuda, seminar nasional, kuliah umum, dan kegiatan mahasiswa berskala besar dengan akses foyer dan area registrasi yang luas.",
    id: "auditorium-ccr",
    images: [
      { altText: "Auditorium CCR dengan panggung dan kursi utama", isCover: true, url: "fixture:auditorium" },
      { altText: "Foyer Auditorium CCR untuk registrasi peserta", url: "fixture:foyer" },
      { altText: "Area kursi Auditorium CCR dari sisi balkon", url: "fixture:auditorium-side" },
    ],
    location: "Kampus IPB Dramaga, Gedung CCR",
    name: "Auditorium CCR",
    openHoursSummary: "Senin-Jumat, 08.00-21.00",
    price: {
      amountRupiah: 2500000,
      isFree: false,
      summary: "Rp2.500.000 / kegiatan",
    },
    priceSummary: "Rp2.500.000 / kegiatan",
    ratingAverage: 4.8,
    reviewCount: 42,
    reviews: [
      {
        authorName: "BEM KM IPB",
        comment: "Alur masuk peserta jelas dan fasilitas audio membantu acara berjalan rapi.",
        createdAt: "2026-04-18",
        id: "review-1",
        rating: 5,
      },
      {
        authorName: "Himalkom",
        comment: "Kapasitas besar, tetapi panitia perlu datang lebih awal untuk pengecekan perangkat.",
        createdAt: "2026-03-30",
        id: "review-2",
        rating: 4,
      },
    ],
  },
  {
    capacity: 90,
    category: "Ruang Rapat",
    categorySlug: "ruang-rapat",
    contact: {
      email: "fmipa@apps.ipb.ac.id",
      name: "Sekretariat FMIPA",
      phone: "0251-8625481",
    },
    coverImageUrl: "fixture:seminar",
    description:
      "Ruang seminar dengan konfigurasi fleksibel untuk presentasi akademik, lokakarya, dan diskusi organisasi tingkat fakultas.",
    id: "ruang-seminar-fmipa",
    images: [
      { altText: "Ruang Seminar FMIPA dengan meja diskusi", isCover: true, url: "fixture:seminar" },
      { altText: "Proyektor dan layar presentasi Ruang Seminar FMIPA", url: null },
    ],
    location: "Fakultas MIPA, Lantai 2",
    name: "Ruang Seminar FMIPA",
    openHoursSummary: "Senin-Sabtu, 07.30-18.00",
    price: {
      amountRupiah: 0,
      isFree: true,
      summary: "Gratis untuk organisasi mahasiswa terverifikasi",
    },
    priceSummary: "Gratis untuk organisasi mahasiswa terverifikasi",
    ratingAverage: 4.5,
    reviewCount: 18,
    reviews: [
      {
        authorName: "UKM Riset",
        comment: "Nyaman untuk sesi panel dan mudah diakses dari area fakultas.",
        createdAt: "2026-02-21",
        id: "review-3",
        rating: 5,
      },
    ],
  },
  {
    capacity: 650,
    category: "Auditorium",
    categorySlug: "auditorium",
    contact: {
      email: null,
      name: "Direktorat Fasilitas",
      phone: "0251-8623315",
    },
    coverImageUrl: null,
    description:
      "Gedung serbaguna untuk seremoni, kuliah umum, dan pertemuan besar yang membutuhkan akses panggung serta area penerima tamu.",
    id: "graha-widya-wisuda",
    images: [{ altText: "Gedung Graha Widya Wisuda", isCover: true, url: null }],
    location: "Kampus IPB Dramaga, Jalan Agatis",
    name: "Gedung Graha Widya Wisuda dengan Nama Sangat Panjang untuk Menguji Pemotongan Teks",
    openHoursSummary: "Senin-Jumat, 08.00-20.00",
    price: {
      amountRupiah: 1500000,
      isFree: false,
      summary: "Rp1.500.000 / kegiatan",
    },
    priceSummary: "Rp1.500.000 / kegiatan",
    ratingAverage: null,
    reviewCount: 0,
    reviews: [],
  },
  {
    capacity: 48,
    category: "Laboratorium",
    categorySlug: "laboratorium",
    contact: {
      email: "bio@apps.ipb.ac.id",
      name: "Laboran Biologi",
      phone: "0251-8627701",
    },
    coverImageUrl: "fixture:lab",
    description:
      "Laboratorium pembelajaran dengan meja praktikum, wastafel, dan area instruktur untuk kegiatan akademik terjadwal.",
    id: "laboratorium-biologi-dasar",
    images: [{ altText: "Laboratorium Biologi Dasar dengan meja praktikum", isCover: true, url: "fixture:lab" }],
    location: "Departemen Biologi, Gedung B",
    name: "Laboratorium Biologi Dasar",
    openHoursSummary: "Senin-Jumat, 07.00-16.00",
    price: {
      amountRupiah: 0,
      isFree: true,
      summary: "Gratis untuk kegiatan akademik",
    },
    priceSummary: "Gratis untuk kegiatan akademik",
    ratingAverage: 4.2,
    reviewCount: 9,
    reviews: [],
  },
  {
    capacity: 140,
    category: "Ruang Kelas",
    categorySlug: "ruang-kelas",
    contact: {
      email: "tpb@apps.ipb.ac.id",
      name: "Pengelola TPB",
      phone: "0251-8621000",
    },
    coverImageUrl: "fixture:classroom",
    description: "Ruang kelas besar untuk kuliah umum, pelatihan, dan forum mahasiswa dengan fasilitas layar dan tata suara dasar.",
    id: "kelas-besar-tpb-a101",
    images: [{ altText: "Ruang Kelas Besar TPB A101", isCover: true, url: "fixture:classroom" }],
    location: "Gedung TPB, Lantai 1",
    name: "Kelas Besar TPB A101",
    openHoursSummary: "Senin-Jumat, 07.00-17.00",
    price: {
      amountRupiah: 350000,
      isFree: false,
      summary: "Rp350.000 / kegiatan",
    },
    priceSummary: "Rp350.000 / kegiatan",
    ratingAverage: 4.1,
    reviewCount: 14,
    reviews: [],
  },
  {
    capacity: 220,
    category: "Ruang Terbuka",
    categorySlug: "ruang-terbuka",
    contact: {
      email: "faperta@apps.ipb.ac.id",
      name: "Sekretariat Faperta",
      phone: "0251-8629350",
    },
    coverImageUrl: "fixture:outdoor",
    description:
      "Area terbuka hijau untuk pameran karya, bazar organisasi, dan kegiatan komunitas yang membutuhkan sirkulasi pengunjung luas.",
    id: "plaza-faperta",
    images: [{ altText: "Plaza Faperta dengan area terbuka hijau", isCover: true, url: "fixture:outdoor" }],
    location: "Fakultas Pertanian",
    name: "Plaza Faperta",
    openHoursSummary: "Setiap hari, 07.00-18.00",
    price: {
      amountRupiah: 500000,
      isFree: false,
      summary: "Rp500.000 / kegiatan",
    },
    priceSummary: "Rp500.000 / kegiatan",
    ratingAverage: 4.6,
    reviewCount: 11,
    reviews: [],
  },
];

export const facilityCatalogItems = facilityDetails.map(
  ({ contact, description, images, price, reviews, ...catalogItem }) => catalogItem,
);
